FROM php:8.2-apache

WORKDIR /var/www/html

COPY . . 

#ajoute la directive ServerName localhost au fichier de configuration d'Apache pour définir le nom du serveur.
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

#met à jour les paquets disponibles et installe plusieurs dépendances système nécessaires à l'exécution de l'application.
RUN apt-get update \
    && apt-get install -qq -y --no-install-recommends \
    cron \
     vim \
     locales coreutils apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev;

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

#télécharge et installe Composer, un gestionnaire de dépendances PHP, puis le déplace vers un emplacement accessible dans le chemin système.
RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
   mv composer.phar /usr/local/bin/composer

#installent et configurent différentes extensions PHP
RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql mysqli gd opcache intl zip calendar dom mbstring zip gd xsl && a2enmod rewrite

#installe l'extension PHP APCu et l'active dans la configuration PHP.
RUN pecl install apcu && docker-php-ext-enable apcu

#ajoute un script pour installer des extensions PHP personnalisées depuis un fichier externe.   
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

#donnent les droits d'exécution au script ajouté précédemment et installent l'extension PHP AMQP.
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions amqp

WORKDIR /var/www/html